version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    # depends_on:
    #   - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DB=product_reviews
    volumes:
      - .:/app
    networks:
      - app-network

  # db:
  #   image: mysql:8.0
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_USER: admin
  #     MYSQL_PASSWORD: admin
  #     MYSQL_DATABASE: product_reviews
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ./mysql_data:/var/lib/mysql
  #     - ./mysql-init:/docker-entrypoint-initdb.d
  #   networks:
  #     - app-network

# volumes:
#   mysql_data:

networks:
  app-network:
